### ISSUE TITLE
HELP: Where is the examplesite？

### ISSUE THREAD

**Issue by ghost** [ololiuhqui/magnolia-free-hugo-theme#1]
Excuse me. I' ve a question about the forth step in install. Thanks!!

**Comment by ololiuhqui** [comment]
Hi! I was working on the theme and i forgot to update the docs after moving the exampleSite on its own branch, thank you for making me notice.

Fixed it with 461370e

You can follow the new instructions to install:
https://github.com/ololiuhqui/magnolia-free-hugo-theme/tree/main?tab=readme-ov-file#quick-start-how-to-install-

I will create a development branch for working on updates.

**Comment by shuoouyang** [comment]
Sorry to bother you again, thank you for receiving your reply！ 

But I still have some problems. Based on the new installation steps, I don't quite understand what step 3 means. I studied it for a long time and downloaded the theme with a new command `git clone -b exampleSite --recurse-submodules https://github.com/ololiuhqui/magnolia-free-hugo-theme`, but when I type hugo-serve--d it showed error `Error: command error: Unable to locate config file or config directory. Perhaps you need to create a new site Run hugo help new'for details`

I would really appreciate it, if you could help me! Thank you very much!
